# Generated by Django 5.1.3 on 2025-02-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
