# Generated by Django 5.1.3 on 2025-02-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhub', '0002_categorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
