# Generated by Django 5.1.3 on 2025-02-22 20:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhub', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
